# DigitalOcean App Platform Specification
# Deploy with: doctl apps create --spec .do/app.yaml
# 
# This is the EASIEST way to deploy - no droplet management needed!
# DigitalOcean handles scaling, SSL, and container orchestration.

name: guardr

region: nyc

services:
  - name: api
    github:
      repo: calebmills99/guardrV6
      branch: main
      deploy_on_push: true
    
    dockerfile_path: Dockerfile
    
    http_port: 5000
    
    instance_size_slug: basic-xxs  # $5/mo - upgrade as needed
    instance_count: 1
    
    health_check:
      http_path: /health
      initial_delay_seconds: 30
      period_seconds: 10
    
    routes:
      - path: /
    
    envs:
      - key: RUST_LOG
        value: info
      - key: DATABASE_URL
        value: "sqlite:///app/data/guardr.db?mode=rwc"
      # Add secrets via DigitalOcean dashboard, not here!
      # - key: API_KEY
      #   type: SECRET

# Optional: Add a managed database instead of SQLite
# databases:
#   - name: guardr-db
#     engine: PG
#     version: "15"
#     size: db-s-dev-database  # $15/mo

# Optional: Add a static site for the frontend
# static_sites:
#   - name: website
#     github:
#       repo: calebmills99/guardrV6
#       branch: main
#     source_dir: website
#     build_command: npm run build
#     output_dir: out
