# DigitalOcean App Platform Specification
# Deploy with: doctl apps create --spec .do/app.yaml
# 
# This is the EASIEST way to deploy - no droplet management needed!
# DigitalOcean handles scaling, SSL, and container orchestration.

name: guardr

region: nyc

services:
  - name: api
    github:
      repo: calebmills99/guardrV6
      branch: main
      deploy_on_push: true
    
    dockerfile_path: Dockerfile
    
    http_port: 5000
    
    instance_size_slug: basic-xxs  # $5/mo - upgrade as needed
    instance_count: 1
    
    health_check:
      http_path: /health
      initial_delay_seconds: 30
      period_seconds: 10
    
    routes:
      - path: /api

    envs:
      - key: RUST_LOG
        value: info
      - key: DATABASE_URL
        value: "sqlite:/app/data/guardr.db?mode=rwc"
      - key: GUARDR__DATABASE__SQLITE_URL
        value: "sqlite:/app/data/guardr.db?mode=rwc"
      # Add secrets via DigitalOcean dashboard, not here!
      # - key: API_KEY
      #   type: SECRET

# Optional: Add a managed PostgreSQL database (requires code changes)
# databases:
#   - name: guardr-db
#     engine: PG
#     version: "16"
#     size: db-s-dev-database  # $15/mo

# Frontend website
static_sites:
  - name: website
    github:
      repo: calebmills99/guardrV6
      branch: main
      deploy_on_push: true
    source_dir: website
    build_command: npm install && npm run build
    output_dir: out
    routes:
      - path: /
    domains:
      - domain: guardr.app
        type: PRIMARY
      - domain: www.guardr.app
        type: ALIAS
