'use client';

import {
  FileText,
  Shield,
  Lock,
  Users,
  CreditCard,
  AlertTriangle,
  Scale,
  Ban,
  Mail,
  ArrowRight,
  CheckCircle,
  XCircle,
  Gavel,
  RefreshCw,
  BookOpen
} from 'lucide-react';
import Card from '@/components/ui/Card';
import Badge from '@/components/ui/Badge';
import Button from '@/components/ui/Button';
import Link from 'next/link';

const keyCallouts = [
  {
    icon: Users,
    title: '18+ Only',
    description: 'You must be at least 18 years old to use Guardr.',
    color: 'text-primary-400',
  },
  {
    icon: Shield,
    title: 'Safety Tool, Not a Guarantee',
    description: 'Guardr provides risk assessments—not absolute safety guarantees.',
    color: 'text-secondary-400',
  },
  {
    icon: Ban,
    title: 'No Stalking or Harassment',
    description: 'Using Guardr to stalk, harass, or dox anyone is strictly prohibited.',
    color: 'text-danger-500',
  },
];

const sections = [
  {
    number: '1',
    title: 'Acceptance of Terms',
    icon: CheckCircle,
    paragraphs: [
      'By accessing or using Guardr ("the Service"), you agree to be bound by these Terms of Service ("Terms"). If you do not agree to these Terms, you may not use the Service.',
      'We may update these Terms from time to time. Continued use of the Service after changes constitutes acceptance of the updated Terms. We will notify you of material changes at least 30 days in advance.',
    ],
  },
  {
    number: '2',
    title: 'Service Description',
    icon: Shield,
    paragraphs: [
      'Guardr is an AI-powered dating safety platform that provides identity verification, digital footprint analysis, and risk assessment services. The Service uses open-source intelligence (OSINT) techniques, publicly available data, and AI analysis to generate safety reports about individuals you may encounter in online dating.',
      'The Service is designed as an informational tool to help you make safer decisions. It does not guarantee the safety, identity, or intentions of any individual.',
    ],
  },
  {
    number: '3',
    title: 'User Accounts & Registration',
    icon: Users,
    paragraphs: [
      'To use certain features of the Service, you must create an account. You agree to provide accurate, current, and complete information during registration and to keep your account information updated.',
      'You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account. You must notify us immediately of any unauthorized use.',
      'You must be at least 18 years of age to create an account and use the Service.',
    ],
  },
  {
    number: '4',
    title: 'Acceptable Use',
    icon: Scale,
    paragraphs: [
      'Guardr is intended solely for personal safety purposes in the context of online dating. You agree to use the Service only for its intended purpose.',
    ],
    lists: [
      {
        title: 'You may NOT use Guardr to:',
        type: 'prohibited' as const,
        items: [
          'Stalk, harass, intimidate, or threaten any individual',
          'Dox or publicly expose private information about any person',
          'Discriminate against individuals based on race, religion, gender identity, sexual orientation, or any protected characteristic',
          'Conduct background checks for employment, housing, or credit decisions',
          'Access the Service through automated means (bots, scrapers) without permission',
          'Circumvent any security measures or rate limits',
          'Resell, redistribute, or commercially exploit safety reports',
        ],
      },
    ],
  },
  {
    number: '5',
    title: 'Subscription & Billing',
    icon: CreditCard,
    paragraphs: [
      'Guardr offers both free and paid subscription tiers. Paid subscriptions are billed on a recurring basis (monthly or annually) as selected at the time of purchase.',
      'You may cancel your subscription at any time. Cancellation takes effect at the end of the current billing period. No refunds are provided for partial billing periods.',
      'We reserve the right to change pricing with 30 days\' notice. Price changes will not affect your current billing period.',
    ],
  },
  {
    number: '6',
    title: 'Intellectual Property',
    icon: BookOpen,
    paragraphs: [
      'The Service, including its design, features, content, AI models, and underlying technology, is owned by Guardr and protected by intellectual property laws.',
      'Your use of the Service does not grant you any ownership rights. You may not copy, modify, distribute, or reverse-engineer any part of the Service without explicit written permission.',
      'Safety reports generated by the Service are provided for your personal use only and may not be commercially redistributed.',
    ],
  },
  {
    number: '7',
    title: 'Disclaimer & Limitation of Liability',
    icon: AlertTriangle,
    paragraphs: [
      'THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED. WE DO NOT WARRANT THAT THE SERVICE WILL BE UNINTERRUPTED, ERROR-FREE, OR COMPLETELY SECURE.',
      'GUARDR IS AN INFORMATIONAL SAFETY TOOL. IT DOES NOT GUARANTEE THE SAFETY, IDENTITY, TRUSTWORTHINESS, OR INTENTIONS OF ANY INDIVIDUAL. SAFETY REPORTS ARE BASED ON PUBLICLY AVAILABLE DATA AND AI ANALYSIS, WHICH MAY BE INCOMPLETE OR INACCURATE.',
      'TO THE MAXIMUM EXTENT PERMITTED BY LAW, GUARDR SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES ARISING FROM YOUR USE OF THE SERVICE.',
    ],
  },
  {
    number: '8',
    title: 'Privacy',
    icon: Lock,
    paragraphs: [
      'Your privacy is fundamental to our mission. Our collection, use, and protection of your personal information is governed by our Privacy Policy, which is incorporated into these Terms by reference.',
    ],
    link: { text: 'Read our Privacy Policy', href: '/privacy' },
  },
  {
    number: '9',
    title: 'Termination',
    icon: XCircle,
    paragraphs: [
      'We may suspend or terminate your account if you violate these Terms, particularly the Acceptable Use provisions. We may also terminate accounts that have been inactive for an extended period.',
      'Upon termination, your right to use the Service ceases immediately. We will delete your account data in accordance with our Privacy Policy.',
      'You may delete your account at any time through your account settings or by contacting us.',
    ],
  },
  {
    number: '10',
    title: 'Governing Law',
    icon: Gavel,
    paragraphs: [
      'These Terms shall be governed by and construed in accordance with the laws of the United States. Any disputes arising from these Terms or the Service shall be resolved through binding arbitration, except where prohibited by law.',
    ],
  },
  {
    number: '11',
    title: 'Changes to Terms',
    icon: RefreshCw,
    paragraphs: [
      'We reserve the right to modify these Terms at any time. Material changes will be communicated via email or prominent notice on the platform at least 30 days before they take effect.',
      'Your continued use of the Service after the effective date of changes constitutes acceptance of the updated Terms.',
    ],
  },
  {
    number: '12',
    title: 'Contact',
    icon: Mail,
    paragraphs: [
      'If you have questions about these Terms of Service, please contact us at support@guardr.app or visit our contact page.',
    ],
    link: { text: 'Contact Us', href: '/contact' },
  },
];

export default function Terms() {
  return (
    <div className="min-h-screen">
      {/* Hero */}
      <section className="relative py-24 lg:py-32 overflow-hidden bg-hero-night">
        <div className="absolute inset-0 opacity-30 bg-grid-pattern" />
        <div className="absolute top-20 right-1/4 w-96 h-96 bg-primary-500/10 rounded-full blur-3xl" />

        <div className="container mx-auto px-4 sm:px-6 lg:px-8 relative z-10 text-center">
          <div className="w-32 h-1 pride-gradient mx-auto mb-8 rounded-full shadow-glow-neutral-strong" />

          <Badge variant="primary" pill className="mb-6 text-sm">
            <FileText className="w-4 h-4 mr-1 inline" />
            Terms of Service
          </Badge>

          <h1 className="text-5xl lg:text-7xl font-bold mb-6">
            <span className="gradient-text">Terms of</span>
            <br />
            Service
          </h1>

          <p className="text-lg text-white/60">
            Effective: January 2026
          </p>
        </div>
      </section>

      {/* Key Callouts */}
      <section className="py-16 lg:py-20">
        <div className="container mx-auto px-4 sm:px-6 lg:px-8">
          <div className="grid sm:grid-cols-3 gap-6 max-w-4xl mx-auto">
            {keyCallouts.map((item) => (
              <Card key={item.title} variant="glass" padding="lg" className="text-center">
                <div className="w-14 h-14 rounded-xl bg-surface-300 flex items-center justify-center mx-auto mb-4">
                  <item.icon className={`w-7 h-7 ${item.color}`} />
                </div>
                <h3 className="text-lg font-semibold mb-2">{item.title}</h3>
                <p className="text-sm text-white/60">{item.description}</p>
              </Card>
            ))}
          </div>
        </div>
      </section>

      {/* Terms Sections */}
      <section className="py-16 lg:py-24 bg-surface-200/50">
        <div className="container mx-auto px-4 sm:px-6 lg:px-8">
          <div className="max-w-3xl mx-auto space-y-8">
            {sections.map((section) => (
              <Card key={section.number} variant="bordered" padding="lg">
                <div className="flex items-center gap-4 mb-6">
                  <div className="w-10 h-10 rounded-lg bg-primary-500/20 flex items-center justify-center flex-shrink-0">
                    <span className="text-primary-400 font-bold text-sm">{section.number}</span>
                  </div>
                  <div className="flex items-center gap-3">
                    <section.icon className="w-5 h-5 text-primary-400" />
                    <h2 className="text-xl font-semibold">{section.title}</h2>
                  </div>
                </div>

                <div className="space-y-4 pl-14">
                  {section.paragraphs.map((text, i) => (
                    <p key={i} className="text-sm text-white/60 leading-relaxed">{text}</p>
                  ))}

                  {section.lists?.map((list) => (
                    <div key={list.title} className="mt-4">
                      <h3 className="text-sm font-semibold text-danger-500 mb-3">{list.title}</h3>
                      <ul className="space-y-2">
                        {list.items.map((item, i) => (
                          <li key={i} className="flex items-start gap-2 text-sm text-white/60">
                            <XCircle className="w-4 h-4 text-danger-500 flex-shrink-0 mt-0.5" />
                            {item}
                          </li>
                        ))}
                      </ul>
                    </div>
                  ))}

                  {section.link && (
                    <Link
                      href={section.link.href}
                      className="inline-flex items-center gap-2 text-sm text-primary-400 hover:underline mt-2"
                    >
                      {section.link.text}
                      <ArrowRight className="w-4 h-4" />
                    </Link>
                  )}
                </div>
              </Card>
            ))}
          </div>
        </div>
      </section>

      {/* CTA */}
      <section className="py-20 lg:py-28">
        <div className="container mx-auto px-4 sm:px-6 lg:px-8 text-center">
          <h2 className="text-3xl lg:text-4xl font-bold mb-4">Questions About Our Terms?</h2>
          <p className="text-lg text-white/70 mb-8 max-w-2xl mx-auto">
            We believe in transparency. If anything is unclear, don&apos;t hesitate to reach out.
          </p>
          <div className="flex flex-col sm:flex-row gap-4 justify-center">
            <Link href="/contact">
              <Button
                variant="primary"
                size="lg"
                icon={ArrowRight}
                iconPosition="right"
              >
                Contact Us
              </Button>
            </Link>
            <Link href="/privacy">
              <Button
                variant="outline"
                size="lg"
              >
                Privacy Policy
              </Button>
            </Link>
          </div>
        </div>
      </section>
    </div>
  );
}
